### ISSUE TITLE
pip package error

### ISSUE THREAD

**Issue by mustafaaykon** [aws-samples/pyflink-getting-started#21]
Whenever i tried to "pip install apache-flink==1.15.2" i am getting error at "pandas 1.1.5" version. Probably it is not compatible with apple slicon M1. I am able to execute "pip install apache-flink==1.16.0" Could you update the repo for 1.16.0 version please ? :)

**Comment by jeremyber-aws** [comment]
Hi @mustafaaykon, Kinesis Data Analytics for Apache Flink does not support v1.16.0 of Apache Flink at this moment, which is why we do not have examples for this. You may need to use x86_64 conda environment like the one described [in this article](https://towardsdatascience.com/python-conda-environments-for-both-arm64-and-x86-64-on-m1-apple-silicon-147b943ffa55). Let me know if that helps

**Comment by jeremyber-aws** [comment]
More details can be found here:
https://github.com/aws-samples/amazon-managed-service-for-apache-flink-examples/tree/main/python/LocalDevelopmentOnAppleSilicon
