### ISSUE TITLE
OutOfMemoryError with the Tumbing Window example

### ISSUE THREAD

**Issue by AgeBeeTen** [aws-samples/pyflink-getting-started#5]
Hi,
the getting-started.py example is running fine on my local but when I try to run the tumbling-windows.py I get the follwoing error:

`Exception in thread "kpl-daemon-0000" java.lang.OutOfMemoryError: Java heap space`

I put data from my local with the stock.py producer onto a Kinesis Data Stream and run the  tumbling-windows.py within Python Spyder 5.0 (Python 3.8) locally.

Any idea why this example causes an error ?
Thanks
Regards

**Comment by jeremyber-aws** [comment]
Hi @AgeBeeTen this issue seems related to the use of the Kinesis Producer Library. The KPL can be configured to hold on to records for a period of time to batch them up before delivering to Kinesis Data Streams. Check your configuration on the KPL to ensure you aren't hanging on to these records for too long. `sink.producer.aggregation-max-count` could be a relevant one here, but see the configuration options for your use case [here](https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/connectors/table/kinesis/#sink-producer)
